# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class AwsSsoUtil < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    url "https://github.com/catpaladin/aws-sso-util/releases/download/v0.2.0/aws-sso-util_0.2.0_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "d3429b729da82705bc23a18c646ce8875548a8496ac421749ef55c7bc311dcb1"

    def install
      bin.install "aws-sso-util"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/catpaladin/aws-sso-util/releases/download/v0.2.0/aws-sso-util_0.2.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "817dea8da38906681e851b96eef70b2de5b850d330f47ba11963fae1143b02f7"

      def install
        bin.install "aws-sso-util"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/catpaladin/aws-sso-util/releases/download/v0.2.0/aws-sso-util_0.2.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7b518f5200a7a055b4b7507c02b803dfee24bc3ab1d39fb1421493c1d4933799"

      def install
        bin.install "aws-sso-util"
      end
    end
  end
end
