# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class AwsSsoUtil < Formula
  desc ""
  homepage ""
  version "0.3.0"

  on_macos do
    url "https://github.com/catpaladin/aws-sso-util/releases/download/v0.3.0/aws-sso-util_0.3.0_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "2745ace7320dd130c5ff1595c12282b6da1793c71c5ff43182ef62fdf5321f33"

    def install
      bin.install "aws-sso-util"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/catpaladin/aws-sso-util/releases/download/v0.3.0/aws-sso-util_0.3.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d20b1a7f1391a6fc04571cd7749157a4ea4433119295dee4ef94322dc3a62416"

      def install
        bin.install "aws-sso-util"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/catpaladin/aws-sso-util/releases/download/v0.3.0/aws-sso-util_0.3.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c7f93223f18a07f281032addb4649174ca9549fad0fc38379327c6c30f3fd700"

      def install
        bin.install "aws-sso-util"
      end
    end
  end
end
