# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class AwsSsoUtil < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    url "https://github.com/catpaladin/aws-sso-util/releases/download/v0.1.0/aws-sso-util_0.1.0_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "cef610a9c91d45dca2e89873efff0f8795d8c3239872b9657f7302d289277e1a"

    def install
      bin.install "aws-sso-util"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/catpaladin/aws-sso-util/releases/download/v0.1.0/aws-sso-util_0.1.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0529fe08a3b8fd20a17145a5ceef7a3d1434b4810cb9cc0133d62f1808334799"

      def install
        bin.install "aws-sso-util"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/catpaladin/aws-sso-util/releases/download/v0.1.0/aws-sso-util_0.1.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1ac7314b9b2f0d0879041dff48595c8293cef80fd2385e2fe7ef8087e093b8c4"

      def install
        bin.install "aws-sso-util"
      end
    end
  end
end
