builds:
  - binary: aws-sso-util
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto
  mode: append

universal_binaries:
  - replace: true

brews:
  - tap:
      owner: catpaladin
      name: aws-sso-util
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    custom_require: "lib/custom_download_strategy"
    commit_author:
      name: catpaladin
      email: mjsahari@gmail.com
    folder: HomebrewFormula

checksum:
  name_template: 'checksums.txt'

